languageCode = "id"
languageName = "Indonesian"
displayName = "ID"
isoCode = "id"
weight = 1
rtl = false

title = "Jundi Mubarok"
#logo = "default-monochrome-white.svg"
#secondaryLogo = "default-monochrome-white.svg"
description = "Saya suka berbagi cerita tentang pengalaman sehari-hari dan terkadang berbagi tutorial ringan seputar teknologi dan website."
copyright = "âš¡by [Blowfish](https://blowfish.page). [My opinions](http://creativecommons.org/licenses/by-nc/4.0/) are my own" #custom copyright footer
dateFormat = "2 January 2006"

 [author]
   name = "Jundi Mubarok"
   image = "img/author-baru.jpg"
   imageQuality = 30
   headline = "Certified Writer by **[CIW](https://certifiedimpactfulwriter.com)**" # dibawah foto profil homepage
   bio = "Write Stories Share Inspiration" #di profil artikel. 
   links = [
#     {  facebook = "https://facebook.com/jundi.mubarok.14" },
      { instagram = "https://instagram.com/jundi.mubarok" },
      { threads = "https://www.threads.net/@jundi.mubarok" },
#     { email = "mailto:jundi@impactfulwriter.id" },
#     { link = "https://nihbuatjajan.com/jundi/" },
#     { telegram = "https://t.me/jundipost" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },     
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/jundimubarok" },
   ]
